/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.awt.Dimension;
import java.awt.FlowLayout;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import org.example.ui.ButtonLogic;

public class App {

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        JLabel label = new JLabel();
        JButton startButton = new JButton();
        JPanel panel = new JPanel();

        panel.add(label);
        panel.add(startButton);
        panel.setPreferredSize(new Dimension(150, 150));
        panel.setLayout(new FlowLayout());

        label.setText("Pense em prato que gosta");
        label.setHorizontalAlignment(JLabel.CENTER);
        label.setVerticalAlignment(JLabel.CENTER);

        startButton.setText("OK");
        startButton.addActionListener(new ButtonLogic());

        frame.setSize(280, 135);
        frame.setTitle("Jogo Gourmet");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        frame.add(panel);
        frame.setLayout(new FlowLayout(FlowLayout.CENTER));
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }
}
